=begin
#Merge Accounting API

#The unified API for building rich integrations with multiple Accounting & Finance platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'date'
require 'time'

module MergeAccountingClient
  # # The CashFlowStatement Object ### Description The `CashFlowStatement` object is used to represent a company's cash flow statement.  ### Usage Example Fetch from the `LIST CashFlowStatements` endpoint and view a company's cash flow statements.
  class CashFlowStatement
    attr_accessor :id

    # The third-party API ID of the matching object.
    attr_accessor :remote_id

    attr_accessor :remote_data

    # The cash flow statement's name.
    attr_accessor :name

    # The cash flow statement's start period.
    attr_accessor :start_period

    # The cash flow statement's end period.
    attr_accessor :end_period

    # Cash and cash equivalents at the beginning of the cash flow statement's period.
    attr_accessor :cash_at_beginning_of_period

    # Cash and cash equivalents at the beginning of the cash flow statement's period.
    attr_accessor :cash_at_end_of_period

    attr_accessor :operating_activities

    attr_accessor :investing_activities

    attr_accessor :financing_activities

    # The time that cash flow statement was generated by the accounting system.
    attr_accessor :remote_generated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'remote_id' => :'remote_id',
        :'remote_data' => :'remote_data',
        :'name' => :'name',
        :'start_period' => :'start_period',
        :'end_period' => :'end_period',
        :'cash_at_beginning_of_period' => :'cash_at_beginning_of_period',
        :'cash_at_end_of_period' => :'cash_at_end_of_period',
        :'operating_activities' => :'operating_activities',
        :'investing_activities' => :'investing_activities',
        :'financing_activities' => :'financing_activities',
        :'remote_generated_at' => :'remote_generated_at'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'remote_id' => :'String',
        :'remote_data' => :'Array<RemoteData>',
        :'name' => :'String',
        :'start_period' => :'Time',
        :'end_period' => :'Time',
        :'cash_at_beginning_of_period' => :'Float',
        :'cash_at_end_of_period' => :'Float',
        :'operating_activities' => :'Array<ReportItem>',
        :'investing_activities' => :'Array<ReportItem>',
        :'financing_activities' => :'Array<ReportItem>',
        :'remote_generated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'remote_id',
        :'remote_data',
        :'name',
        :'start_period',
        :'end_period',
        :'cash_at_beginning_of_period',
        :'cash_at_end_of_period',
        :'remote_generated_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MergeAccountingClient::CashFlowStatement` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MergeAccountingClient::CashFlowStatement`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'remote_id')
        self.remote_id = attributes[:'remote_id']
      end

      if attributes.key?(:'remote_data')
        if (value = attributes[:'remote_data']).is_a?(Array)
          self.remote_data = value
        end
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'start_period')
        self.start_period = attributes[:'start_period']
      end

      if attributes.key?(:'end_period')
        self.end_period = attributes[:'end_period']
      end

      if attributes.key?(:'cash_at_beginning_of_period')
        self.cash_at_beginning_of_period = attributes[:'cash_at_beginning_of_period']
      end

      if attributes.key?(:'cash_at_end_of_period')
        self.cash_at_end_of_period = attributes[:'cash_at_end_of_period']
      end

      if attributes.key?(:'operating_activities')
        if (value = attributes[:'operating_activities']).is_a?(Array)
          self.operating_activities = value
        end
      end

      if attributes.key?(:'investing_activities')
        if (value = attributes[:'investing_activities']).is_a?(Array)
          self.investing_activities = value
        end
      end

      if attributes.key?(:'financing_activities')
        if (value = attributes[:'financing_activities']).is_a?(Array)
          self.financing_activities = value
        end
      end

      if attributes.key?(:'remote_generated_at')
        self.remote_generated_at = attributes[:'remote_generated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          remote_id == o.remote_id &&
          remote_data == o.remote_data &&
          name == o.name &&
          start_period == o.start_period &&
          end_period == o.end_period &&
          cash_at_beginning_of_period == o.cash_at_beginning_of_period &&
          cash_at_end_of_period == o.cash_at_end_of_period &&
          operating_activities == o.operating_activities &&
          investing_activities == o.investing_activities &&
          financing_activities == o.financing_activities &&
          remote_generated_at == o.remote_generated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, remote_id, remote_data, name, start_period, end_period, cash_at_beginning_of_period, cash_at_end_of_period, operating_activities, investing_activities, financing_activities, remote_generated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = MergeAccountingClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
