=begin
#Merge Accounting API

#The unified API for building rich integrations with multiple Accounting & Finance platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MergeAccountingClient::AccountingPeriodsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountingPeriodsApi' do
  before do
    # run before each test
    @api_instance = MergeAccountingClient::AccountingPeriodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountingPeriodsApi' do
    it 'should create an instance of AccountingPeriodsApi' do
      expect(@api_instance).to be_instance_of(MergeAccountingClient::AccountingPeriodsApi)
    end
  end

  # unit tests for accounting_periods_list
  # Returns a list of &#x60;AccountingPeriod&#x60; objects.
  # @param x_account_token Token identifying the end user.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor The pagination cursor value.
  # @option opts [Boolean] :include_deleted_data Whether to include data that was marked as deleted by third party webhooks.
  # @option opts [Boolean] :include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models.
  # @option opts [Integer] :page_size Number of results to return per page.
  # @return [PaginatedAccountingPeriodList]
  describe 'accounting_periods_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for accounting_periods_retrieve
  # Returns an &#x60;AccountingPeriod&#x60; object with the given &#x60;id&#x60;.
  # @param x_account_token Token identifying the end user.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models.
  # @return [AccountingPeriod]
  describe 'accounting_periods_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
