=begin
#Merge Accounting API

#The unified API for building rich integrations with multiple Accounting & Finance platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MergeAccountingClient::AuditTrailApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuditTrailApi' do
  before do
    # run before each test
    @api_instance = MergeAccountingClient::AuditTrailApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuditTrailApi' do
    it 'should create an instance of AuditTrailApi' do
      expect(@api_instance).to be_instance_of(MergeAccountingClient::AuditTrailApi)
    end
  end

  # unit tests for audit_trail_list
  # Gets a list of audit trail events.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor The pagination cursor value.
  # @option opts [String] :end_date If included, will only include audit trail events that occured before this time
  # @option opts [String] :event_type If included, will only include events with the given event type. Possible values include: &#x60;CREATED_REMOTE_PRODUCTION_API_KEY&#x60;, &#x60;DELETED_REMOTE_PRODUCTION_API_KEY&#x60;, &#x60;CREATED_TEST_API_KEY&#x60;, &#x60;DELETED_TEST_API_KEY&#x60;, &#x60;REGENERATED_PRODUCTION_API_KEY&#x60;, &#x60;INVITED_USER&#x60;, &#x60;TWO_FACTOR_AUTH_ENABLED&#x60;, &#x60;TWO_FACTOR_AUTH_DISABLED&#x60;, &#x60;DELETED_LINKED_ACCOUNT&#x60;, &#x60;CREATED_DESTINATION&#x60;, &#x60;DELETED_DESTINATION&#x60;, &#x60;CHANGED_SCOPES&#x60;, &#x60;CHANGED_PERSONAL_INFORMATION&#x60;, &#x60;CHANGED_ORGANIZATION_SETTINGS&#x60;, &#x60;ENABLED_INTEGRATION&#x60;, &#x60;DISABLED_INTEGRATION&#x60;, &#x60;ENABLED_CATEGORY&#x60;, &#x60;DISABLED_CATEGORY&#x60;, &#x60;CHANGED_PASSWORD&#x60;, &#x60;RESET_PASSWORD&#x60;, &#x60;ENABLED_REDACT_UNMAPPED_DATA_FOR_ORGANIZATION&#x60;, &#x60;ENABLED_REDACT_UNMAPPED_DATA_FOR_LINKED_ACCOUNT&#x60;, &#x60;DISABLED_REDACT_UNMAPPED_DATA_FOR_ORGANIZATION&#x60;, &#x60;DISABLED_REDACT_UNMAPPED_DATA_FOR_LINKED_ACCOUNT&#x60;
  # @option opts [Integer] :page_size Number of results to return per page.
  # @option opts [String] :start_date If included, will only include audit trail events that occured after this time
  # @option opts [String] :user_email If provided, this will return events associated with the specified user email. Please note that the email address reflects the user&#39;s email at the time of the event, and may not be their current email.
  # @return [PaginatedAuditLogEventList]
  describe 'audit_trail_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
