=begin
#Merge Accounting API

#The unified API for building rich integrations with multiple Accounting & Finance platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MergeAccountingClient::WebhookReceiversApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhookReceiversApi' do
  before do
    # run before each test
    @api_instance = MergeAccountingClient::WebhookReceiversApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookReceiversApi' do
    it 'should create an instance of WebhookReceiversApi' do
      expect(@api_instance).to be_instance_of(MergeAccountingClient::WebhookReceiversApi)
    end
  end

  # unit tests for webhook_receivers_create
  # Creates a &#x60;WebhookReceiver&#x60; object with the given values.
  # @param webhook_receiver_request 
  # @param [Hash] opts the optional parameters
  # @return [WebhookReceiver]
  describe 'webhook_receivers_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhook_receivers_list
  # Returns a list of &#x60;WebhookReceiver&#x60; objects.
  # @param [Hash] opts the optional parameters
  # @return [Array<WebhookReceiver>]
  describe 'webhook_receivers_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
