=begin
#Merge Accounting API

#The unified API for building rich integrations with multiple Accounting & Finance platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeAccountingClient::InvoiceTypeEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeAccountingClient::InvoiceTypeEnum do
  let(:instance) { MergeAccountingClient::InvoiceTypeEnum.new }

  describe 'test an instance of InvoiceTypeEnum' do
    it 'should create an instance of InvoiceTypeEnum' do
      expect(instance).to be_instance_of(MergeAccountingClient::InvoiceTypeEnum)
    end
  end
end
